backend:
  name: git-gateway
  # branch: master

media_folder: "/media"
public_folder: "assets"
# publish_mode: "editorial_workflow"



collections:


  # Posts
  - name: "articles"
    label: "Articles"
    folder: "collections/posts"
    media_folder: "/media"
    create: true
    path: "{{slug}}/index"
    editor:
      preview: false

    sortable_fields:
      - "date"
      - "title"
      - "draft"

    fields:
      - label: "Draft"
        name: "draft"
        required: false
        default: false
        widget: "boolean"

      - label: "Featured Image"
        name: "thumbnail"
        required: false
        widget: "image"

      - label: "Date"
        name: "date"
        widget: "datetime"
        default: ""
        format: "YYYY-MM-DD"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Meta Title"
        name: "meta_title"
        widget: "string"
        required: false

      - label: "Meta Description"
        name: "meta_description"
        widget: "string"
        required: false

      - label: "Excerpt"
        name: "excerpt"
        widget: "text"
        required: false

      - label: "Body"
        name: "body"
        widget: "markdown"


# ========================================
  - name: "dataset-one"
    label: "Dataset One"
    folder: "collections/dataset-one"
    create: true
    path: "{{slug}}/index"
    editor:
      preview: false
    sortable_fields:
      - "weight"
      - "title"
    nested:
      depth: 2
    fields:
      - label: "Weight"
        name: "weight"
        required: false
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Meta Title"
        name: "meta_title"
        widget: "string"
        required: false
      - label: "Meta Description"
        name: "meta_description"
        widget: "string"
        required: false
      - label: "Descripiton"
        name: "description"
        widget: "string"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false

