backend:
  name: git-gateway

media_folder: "assets/media"
public_folder: "/media/image"

collections:
  - name: "articles"
    label: "Articles"
    folder: "collections/posts"
    media_folder: "assets/media"
    create: true
    path: "{{slug}}/index"
    editor:
      preview: false

    sortable_fields:
      - "date"
      - "title"
      - "draft"

    fields:
      - label: "Draft"
        name: "draft"
        required: false
        default: false
        widget: "boolean"

      - label: "Featured Image"
        name: "thumbnail"
        required: false
        widget: "image"

      - label: "Date"
        name: "date"
        widget: "datetime"
        default: ""
        format: "YYYY-MM-DD"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Meta Title"
        name: "meta_title"
        widget: "string"
        required: false

      - label: "Meta Description"
        name: "meta_description"
        widget: "string"
        required: false

      - label: "Excerpt"
        name: "excerpt"
        widget: "text"
        required: false

      - label: "Body"
        name: "body"
        widget: "markdown"


# ========================================
  - name: "dataset-one"
    label: "Dataset One"
    folder: "collections/dataset-one"
    media_folder: "assets/media"
    create: true
    path: "{{slug}}/index"
    editor:
      preview: false

    sortable_fields:
      - "date"
      - "title"
      - "draft"

    fields:
      - label: "Draft"
        name: "draft"
        required: false
        default: false
        widget: "boolean"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Meta Title"
        name: "meta_title"
        widget: "string"
        required: false

      - label: "Meta Description"
        name: "meta_description"
        widget: "string"
        required: false

      - label: "Body"
        name: "body"
        widget: "markdown"
